---
title: "Sample of Survey"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}

library(tidyverse)
library(scales)
library(gt)

```

To run this code yourself, please run the main data wrangling document beforehand for the most up to date variables.

## Who was recruited for this study?

```{r include=FALSE}

#setting factor levels for main sample variables

training_df$gender <- factor(training_df$gender, levels = c("Female", "Male", "Non-binary / third gender", "Prefer not to say"))

training_df$education <- factor(training_df$education, levels = c("Postgraduate (e.g. M.Sc, Ph.D)", "Undergraduate University (e.g. BA, B.Sc, B.Ed)", "A-level, or equivalent", "GCSE level, or equivalent", "No formal qualifications", "Other, please specify"))

training_df$Ethnicity.simplified <- factor(training_df$Ethnicity.simplified, levels = c("White", "Asian", "Black", "Mixed", "Other"))

#creating categories from age and political interest

sample_cat <- training_df %>%
  select(gender, education, Ethnicity.simplified, partyID, age, political_interest) %>%
  mutate(age_cat = case_when(
         age >=18 & age <=29 ~ "18-29",
         age >=30 & age <=39 ~ "30-39",
         age >=40 & age <=49 ~ "40-49",
         age >=50 & age <=59 ~ "50-59",
         age >=60 & age <=69 ~ "60-69",
         age >=70 & age <=79 ~ "70-79",
         age >=80 ~ "80+",
         TRUE ~ "unknown"
         )) %>%
  mutate(interest_cat = case_when(
    political_interest == 1 ~ "Not at all interested",
    political_interest == 2 ~ "Not very interested",
    political_interest == 3 ~ "Slightly interested",
    political_interest == 4 ~ "Fairly interested",
    political_interest == 5 ~ "Very interested"
  ))

# Check for NA values in the age_sample column
na_count <- sum(is.na(sample_cat$age_cat))
print(paste("Number of NA values in age_sample:", na_count))

#setting factor levels for age and political interest to arrange order

sample_cat$age_cat <- factor(sample_cat$age_cat, levels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+"))

sample_cat$interest_cat <- factor(sample_cat$interest_cat, levels = c("Not at all interested", "Not very interested", "Slightly interested", "Fairly interested", "Very interested"))

# Function to replace text in a character column
replace_text <- function(column, old_text, new_text) {
  gsub(old_text, new_text, column)
}

#replace some category text

sample_cat <- sample_cat %>%
  mutate(partyID = replace_text(partyID, "Other, please specify___________", "Other"))

#set factor levels for party

sample_cat$partyID <- factor(sample_cat$partyID, levels = c("Conservative", "Labour", "Liberal Democrat", "Green Party", "Reform UK", "Scottish National Party (SNP)", "Alliance Party", "Democratic Unionist Party", "Sinn Féin", "Plaid Cymru", "United Kingdom Independence Party (UKIP)", "Other", "I do not identify with any political party"))

```

```{r echo=FALSE}

# Function to create summary for a categorical variable
summarise_sample <- function(data, var) {
  data %>%
    group_by(!!sym(var)) %>%
    summarise(Frequency = n()) %>%
    mutate(Percentage = round((Frequency / sum(Frequency)) * 100, 2)) %>%
    rename(Category = !!sym(var))
}

# Summarise each categorical variable
gender_summary <- summarise_sample(sample_cat, "gender")
education_summary <- summarise_sample(sample_cat, "education")
ethnicity_summary <- summarise_sample(sample_cat, "Ethnicity.simplified")
partyid_summary <- summarise_sample(sample_cat, "partyID")
age_summary <- summarise_sample(sample_cat, "age_cat")
interest_summary <- summarise_sample(sample_cat, "interest_cat")

# merge

sample <- bind_rows(
  mutate(gender_summary, Variable = "gender"),
  mutate(education_summary, Variable = "education"),
  mutate(ethnicity_summary, Variable = "Ethnicity.simplified"),
  mutate(partyid_summary, Variable = "partyID"),
  mutate(age_summary, Variable = "age_cat"),
  mutate(interest_summary, Variable = "interest_cat")
)

sample <- sample %>%
  select(Variable, Category, Frequency, Percentage)

#reformat %

sample <- sample %>%
  mutate(
    Percentage = Percentage / 100,  # Convert to decimal form
    Percentage = percent(Percentage, accuracy = 0.1)
  )

```

```{r}

#change the variable cat names

sample <- sample %>%
  mutate(Variable = case_when(
    Variable == "gender" ~ "Gender",
    Variable == "education" ~ "Education",
    Variable == "Ethnicity.simplified" ~ "Ethnicity",
    Variable == "partyID" ~ "UK Partisan Affiliation",
    Variable == "age_cat" ~ "Age",
    Variable == "interest_cat" ~ "Political Interest",
    TRUE ~ Variable  # Keep the original value if no match
  ))

# Create table
kable_table <- sample %>%
  select(Variable, Category, Frequency, Percentage) %>%
  kable(format = "html", align = "c", col.names = c("Demographic", "Category", "Frequency", "Percentage (%)")) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),  
    full_width = F,  # Don't stretch the table to full width
    font_size = 12  # Set font size
  ) %>%
  column_spec(3:4, width = "7em") %>%  
  column_spec(1:2, width = "10em") %>% 
  collapse_rows(columns = 1, valign = "top") %>%
  add_header_above(c(" " = 2, "Sample Summary" = 2)) %>%  
  footnote(
    general = "Breakdown of sample by gender, education, ethnicity, UK partisan affiliation, age, and political interest",
    general_title = "Note:",
    footnote_as_chunk = TRUE
  ) %>%
  row_spec(0, bold = TRUE)  

#save_kable(kable_table, "sample_summary.html")

# Use webshot to convert the HTML table to PNG
#webshot("sample_summary.html", "sample_summary.png")

```


